/* Regenerate VOICEOVER.md from src/script.ts, which is the only place the
   lines and their frame windows are written down. Run it after changing a
   line, so the sheet the reader records from cannot drift from the video:

       npm run voiceover

   Node strips the types out of the imported module on its own, so there is no
   build step and no extra dependency to keep current. */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const { SCENES, LINES, FPS, DURATION, timecode, words, wpm } = await import("../src/script.ts");

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const total = LINES.reduce((n, l) => n + words(l.text), 0);

const rows = LINES.map((l) => {
  const scene = SCENES.find((s) => l.from >= s.from && l.from < s.from + s.len);
  return `| ${timecode(l.from)} | ${(l.len / FPS).toFixed(1)}s | ${scene?.name ?? ""} | ${wpm(l)} | ${l.text} |`;
});

const beats = SCENES.map(
  (s) => `- **${timecode(s.from)} ${s.name}** (${(s.len / FPS).toFixed(1)}s). ${s.note}`,
);

const hot = LINES.filter((l) => wpm(l) > 185).map(
  (l) => `- ${timecode(l.from)} reads at ${wpm(l)} words per minute. Shorten it or give it more frames.`,
);

writeFileSync(
  join(root, "VOICEOVER.md"),
  `# The read

Generated from \`src/script.ts\` by \`npm run voiceover\`. Do not edit this file
by hand: change the line there and run it again, so the sheet and the video
cannot disagree.

${total} words across ${DURATION / FPS} seconds. The silences are deliberate.
Read it flat and unhurried, the way somebody explains a thing they have seen up
close, not the way a movie trailer sells one. Nothing here is a pitch, and the
one number in it has a citation on screen underneath it.

## The beats

${beats.join("\n")}

## The lines

Each line has a window. Land inside it and the captions match the read frame
for frame. The pace column is what the line would have to be read at to fill
its window exactly, so treat it as a ceiling rather than a target.

| In | Hold | Scene | Pace | Line |
| --- | --- | --- | --- | --- |
${rows.join("\n")}

## Recording it

Mono, 48 kHz, one take per line if that is easier, assembled against the
timecodes above. Save it as \`public/voiceover.mp3\` and it is picked up on the
next render; with no file there the trailer plays silent and the captions carry
it, which is also how it should play on a muted phone.

Leave the room tone in rather than gating it hard. A breath before *fifty
points* is worth more than a clean floor.
${hot.length ? `\n## Lines that will not fit\n\n${hot.join("\n")}\n` : ""}`,
);

console.log(`VOICEOVER.md written. ${LINES.length} lines, ${total} words.`);
